print("***update set1 by adding items from set2, except common items***")
print("creating sets...")
s1=set([1,2,3,4,5])
s2=set([1,2,3,6])
print("set 1=",s1)
print("set 2=",s2)
print("updating set1...")
s1=s1.union(s2)
print("printing set1:",s1)